services:
  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - src/.env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
