services:
  product_management_system:
    build:
      context: .
    env_file:
      - src/.env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: always
    command: >
      sh -c "cd src &&
            alembic upgrade head &&
            python main.py"
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - src/.env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
